### ISSUE TITLE
line 476: child.scope()

### ISSUE THREAD

**Issue by lukas1994** [davidchin/angular-endless-scroll#2]
Since child is a jQuery object, there's no scope function.
I think it should be angular.element(child).scope()

**Comment by alexey-shaposhnikov** [comment]
I have the same issue on line 519 (`TypeError: child.scope is not a function`)
`itemIndex = $.inArray(child.scope()[this.expression.item], this.originalItems);`
angular: 1.4.6, jquery: 2.1.4, your lib: 0.0.5

**Comment by taoru** [comment]
Temporary workaround is to ensure jQuery loads before Angular.
