### ISSUE TITLE
Watch not dealing with change in source 

### ISSUE THREAD

**Issue by juliemturner** [davidchin/angular-endless-scroll#4]
Hi, Really like this addition to deal with large endless scrolling lists, it worked great for me until I realized that if my source list changed the UI would not update.  So in my scenario I was binding a repeater to the results of a REST api call and all was well in the world until the user changes the filters on the display and the REST api is called to reload the array, ergo needing to rebind the repeater.  After a little investigation I found the following 2 lines of code fixed the issue.  Not sure if it fundamentally changes what your goal was so I'm just sharing, use as you like.  

In the _watch prototype, I modified your $watchCollection by including the test to see if the originalItems and the arguments arrays were different...

this.scope.$watchCollection(collectionExp, angular.bind(this, function watchCollection() {
                if(this.originalItems && this.items && this.originalItems.length > 0 && JSON.stringify(arguments[0]) !== JSON.stringify(this.originalItems))
                    this.items = [];
                this.update.apply(this, arguments);
          }));

**Comment by amselrock** [comment]
I've the same problem! It seems that your solution works fine... push the fix for next release!

**Comment by iAlirezax** [comment]
I faced the same issue, your solution works just fine.

**Comment by davidchin** [comment]
I pushed an update (ba95b9459713acc866198ff2bec8e84679ef1a56) recently and hopefully it would resolve your issue :) So whenever the reference of a datasource changes, the directive will reset the array of displayed items.
